name: date test
on:
  workflow_dispatch:

jobs:
  date_test:
    name: contributor report
    runs-on: ubuntu-latest

    steps:

    - name: Get dates for last month
      shell: bash
      run: |
        # Calculate the first day of the previous month
        start_date=$(date -d "last month" +%Y-%m-01)

        # Calculate the last day of the previous month
        end_date=$(date -d "$start_date +1 month -1 day" +%Y-%m-%d)

        #Set an environment variable with the date range
        echo $(date)
        echo "START_DATE $start_date"
        echo "END_DATE $end_date"
